### ISSUE TITLE
Howto build on top of last FreeBSD ?

### ISSUE THREAD

**Issue by benrubson** [zfsrogue/freebsd-crypto#6]
Hello,

How can we add support for crypto / ZFS encryption to last FreeBSD release please (10.2 at this moment) ?

What about maintained patches to add / merge to the existing / official FreeBSD ZFS source code ?
Then, we just would have to rebuild the ZFS part.
It would result into the last official FreeBSD ZFS version with just encryption added.

Thank you very much !

Best regards,

Ben

**Comment by lundman** [comment]
It hasn't been updated for a while, I think the procedure is to pull the git repository, add freebsd's git as upstream, then git merge. I can ask `rogue` to do another merge, maybe he has time.

**Comment by benrubson** [comment]
Thank you very much for your answer !

Could we make a merge with the last release of the freebsd code (instead of the master branch) ?
https://github.com/freebsd/freebsd/tree/release/10.2.0

Perhaps we could create a new freebsd-crypto branch each time a new version of freebsd is released ?
`
crypto-<freebsd_version>
`

In addition, I can see that the "ZFS On Linux with crypto patches" project had a lot of commits in the last few months :
https://github.com/zfsrogue/zfs-crypto
Perhaps bug fixes ?
Could we have the different `crypto-<freebsd_version>` branches to come updated with the last bug fixes ?

Thank you again,

Ben

**Comment by zfsrogue** [comment]
big merge, but release/10.2.0 has done. pls test

**Comment by lundman** [comment]
I pulled "release/10.2.0" and tested, sorry it took a while, slow VM. Building and running appears to work for the bare minimal testing at least. We might want to change the bootfs check though, so you can boot a pool with feature encryption, even if you cant boot a dataset with it enabled.

Oh I see you also updated `master`, I'll make sure that compiles too.

**Comment by benrubson** [comment]
rogue, thank you very much for your work and your time, really !
I'm going to make some deep tests on it (IO load, encryption + compression + userquota...), I will let U know.

Goal would be (I say would of course) to use it in a production environment.
What is your feeling regarding this ?
Is there some work still to achieve ? (I saw your README comments regarding "// FIXME" and MACs)

Another question I will face during my tests, any possibility to change the encryption passphrase of an already encrypted filesystem ?

Thank you again !

**Comment by bsdwatch** [comment]
welp, tried to merge the latest CURRENT, seems youve still got some work to do

Unmerged paths:
  (use "git add <file>..." to mark resolution)

```
    both modified:   cddl/contrib/opensolaris/cmd/zfs/zfs_main.c
    both modified:   cddl/contrib/opensolaris/lib/libzfs/common/libzfs_dataset.c
    both modified:   cddl/usr.bin/zinject/Makefile
    both modified:   sys/cddl/contrib/opensolaris/common/zfs/zfs_prop.c
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/dmu_send.c
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sha256.c
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/dmu_send.h
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/dsl_dataset.h
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/zfs_ioctl.h
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/zio.h
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/sys/zio_checksum.h
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/zfs_ioctl.c
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/zio.c
    both modified:   sys/cddl/contrib/opensolaris/uts/common/fs/zfs/zio_checksum.c
```

**Comment by lundman** [comment]
Everytime you merge with current, there will generally be conflicts, that is just how it works when both repos modify the same files. No surprise there

**Comment by bsdwatch** [comment]
Correct, however, being their all in the ZFS area of work, Im inclined to leave it to the maintainer to resolve again, after that, i am quite capable of resolving and merging other CURRENT potential "conflicts" as time progresses.
